"""initial_schema_with_10k_indexes

Revision ID: 60abd8dc1793
Revises: 
Create Date: 2026-10-03 23:04:31.670458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60abd8dc1793'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.drop_index(op.f('ix_reviews_property_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_wishlist_property_id'), table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_user_id'), table_name='wishlist')
    op.drop_table('wishlist')
    op.drop_index(op.f('ix_search_history_city'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_table('search_history')
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('bookings', 'room_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('bookings', 'amount_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('bookings', 'check_in_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('bookings', 'duration_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_bookings_provider_order_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_provider_payment_id'), table_name='bookings')
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_property_id'), 'bookings', ['property_id'], unique=False)
    op.create_index(op.f('ix_bookings_razorpay_order_id'), 'bookings', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.drop_constraint(op.f('bookings_user_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_room_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'properties', ['property_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'])
    op.drop_column('bookings', 'booking_status')
    op.drop_column('bookings', 'total_amount')
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'provider_order_id')
    op.drop_column('bookings', 'provider_payment_id')
    op.add_column('kyc_documents', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('kyc_documents', sa.Column('document_url', sa.String(), nullable=True))
    op.add_column('kyc_documents', sa.Column('status', sa.String(), nullable=True))
    op.add_column('kyc_documents', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('kyc_documents', 'document_type',
               existing_type=postgresql.ENUM('AADHAAR', 'OWNERSHIP', name='kycdocumenttype'),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('ix_kyc_documents_property_id'), table_name='kyc_documents')
    op.create_index(op.f('ix_kyc_documents_status'), 'kyc_documents', ['status'], unique=False)
    op.create_index(op.f('ix_kyc_documents_user_id'), 'kyc_documents', ['user_id'], unique=False)
    op.drop_constraint(op.f('kyc_documents_property_id_fkey'), 'kyc_documents', type_='foreignkey')
    op.create_foreign_key(None, 'kyc_documents', 'users', ['user_id'], ['id'])
    op.drop_column('kyc_documents', 'original_filename')
    op.drop_column('kyc_documents', 'file_url')
    op.drop_column('kyc_documents', 'updated_at')
    op.drop_column('kyc_documents', 'property_id')
    op.drop_column('kyc_documents', 'created_at')
    op.alter_column('properties', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('properties', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('properties', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('properties', 'type',
               existing_type=postgresql.ENUM('HOSTEL', 'PG', 'FLAT', name='propertytype'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('properties', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'UNISEX', name='propertygender'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('properties', 'verified_badge',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('properties', 'amenities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('properties', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_properties_city_gender_type'), table_name='properties')
    op.create_index('idx_property_lat_lng', 'properties', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_property_search', 'properties', ['city', 'type', 'is_active'], unique=False)
    op.create_index(op.f('ix_properties_created_at'), 'properties', ['created_at'], unique=False)
    op.create_index(op.f('ix_properties_is_active'), 'properties', ['is_active'], unique=False)
    op.create_index(op.f('ix_properties_rating'), 'properties', ['rating'], unique=False)
    op.drop_constraint(op.f('properties_owner_id_fkey'), 'properties', type_='foreignkey')
    op.create_foreign_key(None, 'properties', 'users', ['owner_id'], ['id'])
    op.drop_column('properties', 'verification_status')
    op.drop_column('properties', 'updated_at')
    op.alter_column('rooms', 'property_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('rooms', 'room_type',
               existing_type=postgresql.ENUM('SINGLE', 'DOUBLE', 'TRIPLE', name='roomtype'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('rooms', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('rooms', 'availability_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.create_index(op.f('ix_rooms_availability_count'), 'rooms', ['availability_count'], unique=False)
    op.create_index(op.f('ix_rooms_price'), 'rooms', ['price'], unique=False)
    op.drop_constraint(op.f('rooms_property_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'properties', ['property_id'], ['id'])
    op.drop_column('rooms', 'created_at')
    op.drop_column('rooms', 'updated_at')
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('STUDENT', 'OWNER', 'ADMIN', name='userrole'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'kyc_status',
               existing_type=postgresql.ENUM('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', name='kycstatus'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'kyc_status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', name='kycstatus'),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('STUDENT', 'OWNER', 'ADMIN', name='userrole'),
               nullable=False)
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.add_column('rooms', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('rooms', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_property_id_fkey'), 'rooms', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_rooms_price'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_availability_count'), table_name='rooms')
    op.alter_column('rooms', 'images',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('rooms', 'availability_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rooms', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('rooms', 'room_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('SINGLE', 'DOUBLE', 'TRIPLE', name='roomtype'),
               nullable=False)
    op.alter_column('rooms', 'property_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.add_column('properties', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('verification_status', postgresql.ENUM('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', name='kycstatus'), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.create_foreign_key(op.f('properties_owner_id_fkey'), 'properties', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_properties_rating'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_active'), table_name='properties')
    op.drop_index(op.f('ix_properties_created_at'), table_name='properties')
    op.drop_index('idx_property_search', table_name='properties')
    op.drop_index('idx_property_lat_lng', table_name='properties')
    op.create_index(op.f('ix_properties_city_gender_type'), 'properties', ['city', 'gender', 'type'], unique=False)
    op.alter_column('properties', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('properties', 'amenities',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('properties', 'verified_badge',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('properties', 'gender',
               existing_type=sa.String(),
               type_=postgresql.ENUM('MALE', 'FEMALE', 'UNISEX', name='propertygender'),
               nullable=False)
    op.alter_column('properties', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('HOSTEL', 'PG', 'FLAT', name='propertytype'),
               nullable=False)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('properties', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('properties', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('properties', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.add_column('kyc_documents', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('kyc_documents', sa.Column('property_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('kyc_documents', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('kyc_documents', sa.Column('file_url', sa.VARCHAR(length=800), autoincrement=False, nullable=False))
    op.add_column('kyc_documents', sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'kyc_documents', type_='foreignkey')
    op.create_foreign_key(op.f('kyc_documents_property_id_fkey'), 'kyc_documents', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_kyc_documents_user_id'), table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_status'), table_name='kyc_documents')
    op.create_index(op.f('ix_kyc_documents_property_id'), 'kyc_documents', ['property_id'], unique=False)
    op.alter_column('kyc_documents', 'document_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('AADHAAR', 'OWNERSHIP', name='kycdocumenttype'),
               nullable=False)
    op.drop_column('kyc_documents', 'uploaded_at')
    op.drop_column('kyc_documents', 'status')
    op.drop_column('kyc_documents', 'document_url')
    op.drop_column('kyc_documents', 'user_id')
    op.add_column('bookings', sa.Column('provider_payment_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('provider_order_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('payment_status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='paymentstatus'), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('booking_status', postgresql.ENUM('ACTIVE', 'CANCELLED', 'COMPLETED', name='bookingstatus'), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_room_id_fkey'), 'bookings', 'rooms', ['room_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('bookings_user_id_fkey'), 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_razorpay_order_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_property_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.create_index(op.f('ix_bookings_provider_payment_id'), 'bookings', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_bookings_provider_order_id'), 'bookings', ['provider_order_id'], unique=False)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'duration_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'check_in_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('bookings', 'amount_paid',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('bookings', 'room_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.create_table('search_history',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('min_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'UNISEX', name='propertygender'), autoincrement=False, nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('radius_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('search_history_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('search_history_pkey'))
    )
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_search_history_city'), 'search_history', ['city'], unique=False)
    op.create_table('wishlist',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('wishlist_property_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('wishlist_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('wishlist_pkey')),
    sa.UniqueConstraint('user_id', 'property_id', name=op.f('uq_wishlist_user_property'))
    )
    op.create_index(op.f('ix_wishlist_user_id'), 'wishlist', ['user_id'], unique=False)
    op.create_index(op.f('ix_wishlist_property_id'), 'wishlist', ['property_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('reviews_property_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reviews_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey')),
    sa.UniqueConstraint('property_id', 'user_id', name=op.f('uq_reviews_property_user'))
    )
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_property_id'), 'reviews', ['property_id'], unique=False)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
